### ISSUE TITLE
adding option to context menu

### ISSUE THREAD

**Issue by erwindenboer** [ckuhlmann/lt2circuitikz#7]
Hello,

I want to ask if you could write a manual to add this python script to the windows context menu. This is python script tool is useful! However, every time I need to look up the exact command instruction from this website. It is more user-friendly to add an option to the windows context menu which executes the conversion instead of typing everything in command prompt.

**Comment by ckuhlmann** [comment]
Hi,
I won't have time to add a context menu integration any time soon, but you should look at the batch files (.bat). Using these as a template you can easily write your own for your document structure. Then running the script is as simple as double clicking a bat file. 

Another idea is to write a python script that searches your document directory structure for new or changed asc files. Then call the conversion script for all changed files from python. This way you can build all files for your entire latex document and start a latex compile with a single python script call, which is very convenient. 

I have attached the scripts I used for my thesis to do a mass compile of the circuit graphics. The python code might not be very pretty, but it worked for me. Maybe you can use these as a starting point to write your own script.

[compile_scripts.zip](https://github.com/ckuhlmann/lt2circuitikz/files/9427819/compile_scripts.zip)
